### ISSUE TITLE
Missing founding year

### ISSUE THREAD

**Issue by AaronGullickson** [AaronGullickson/system_generation#16]
Pioche has no founding year

**Comment by AaronGullickson** [comment]
I have gone back to the original data, and I can confirm that there is no founding year to start with. Pioche starts with a faction of PIND in the planet data and has faction events, so no way to determine founding date.

**Comment by HammerGS** [comment]
The Sarna Data here is accurate, planet has a canon write up.  Interstellar Expeditions pg 83

![image](https://user-images.githubusercontent.com/13752452/64294815-f6f0d600-cf2c-11e9-86eb-0ef87c13be91.png)

**Comment by AaronGullickson** [comment]
So the founding year should be 2585.

**Comment by AaronGullickson** [comment]
I have confirmed that Pioche is the only planet with this problem. I will fix this and Issue #17 manually

**Comment by AaronGullickson** [comment]
Fixed in the input data manually
