### ISSUE TITLE
Saggina has UND faction

### ISSUE THREAD

**Issue by AaronGullickson** [AaronGullickson/system_generation#17]
I am still losing one planet due to unknown faction type. The planet is Saggina and these are its faction events:

```r
        date event
1 2271-01-01   UND
2 3095-01-01    IE
```

The issue is UND in 2271-01-01. This is coded as an IE planet later. Is that Interstellar Expeditions? Should it really be founded on 3095 and not 2271?

**Comment by HammerGS** [comment]
Here are the forum notes - https://bg.battletech.com/forums/index.php?topic=65940.msg1525500#msg1525500

I'd say discovered in 3095

**Comment by AaronGullickson** [comment]
Ok, so its potentially apocryphal. I will set its founding date to 3095.

**Comment by AaronGullickson** [comment]
Ok, I decided to just check and see if there were any other cases of UND factions in our base data as that could create problems and I found one more case for the planet of Juniper. Here are its faction entries:

```r
Juniper
        date event
1 2271-01-01   UND
2 2783-01-01    LA
3 2821-01-01   ABN
```
Thoughts on how to handle this case? I am wondering if it was maybe supposed to be IND rather than UND, since it was ultimately part of the Lyran Alliance.

**Comment by HammerGS** [comment]
Re Juniper - pg 62 from 1st "such as Juniper, a Kannon Shire colony barely fifteen years old when Kurita raiders hit the main settlement and its surrounding lake valley with strontium-laced nuclear ordnance."

So the data is accurate.

**Comment by AaronGullickson** [comment]
@HammerGS Just to be clear, 2783-01-01 should be the first date not 2271-01-01?

**Comment by HammerGS** [comment]
Yes, the colony was a new colony and based of the dates 1st SW they founded it in 2783 and Kurita killed it good in 2798, but the SUCs data has rounded it to the end of the 1st SW

**Comment by AaronGullickson** [comment]
Ok so I need to delete the UND event for Saggina.

**Comment by AaronGullickson** [comment]
Fixed in the input data manually
