### ISSUE TITLE
Waystation systems

### ISSUE THREAD

**Issue by AaronGullickson** [AaronGullickson/system_generation#24]
Some of the connectors have faction change events. I need to add these back in.

**Comment by AaronGullickson** [comment]
I think this is actually a bigger issue of "waystation" systems that have some kind of space station/moon base etc. that a faction claims. These should be different from connectors but should not necessarily be habitable planets. I think the idea would be to just assign a static small population to one of the planets that represents the colony. SIC codes can be fairly static as well. Recharge stations should be more likely than average. HPGs are a no. 

That should be easy enough to generate, but I need a list of id's for the actual waystation systems in our data.

**Comment by AaronGullickson** [comment]
Here are clan waystations from Explorer Corps:

Trinity, surface garrision
Cambridge Perimeter Defense Station, orbital fleet base
Santiago IV, garrison
Transfer J239H2, orbital cargo transfer
St. Jean - surface cargo storage/occupied colony of Fransciscan monks
Wolf Orbital 82 - orbital fleet base
Transfer Station P3 - orbital cargo way station
Transfer Station P9 - orbital cargo way station/fleet base
Harris - Surface garrison
Wark - garrison
Kinbrace- surface cargo station
Ramsey - surface cargo station
Trelleborg - fleet base
Gwithian - garrison/occupied colony
Salonika - fleet base
Ctesiphon - surface cargo way station
Transfer Facility 4 - surface cargo way station
Suda Bay - fleet base
Ghent - Garrison
Nouveaux Paris - occupied colony
Bazaar - surface trading post
Attenbrooks - orbital trading post/fleet  base

If its an occupied colony, then we should definitely assume habitability and run a colony as normal, so it shouldn't show up as a waystation. However,  I am noticing rather large population sizes in some cases(6 million monks on St. Jean and 15 million on Gwithian). I suspect that these are being recorded as Clan factions in 3047 for the base population calculation, leading to the large sizes. 

For the other cases, of surface garrisons, I am not sure whether we should force a habitable planet. Its possible some of these are just "moon bases" on uninhabited worlds or moons.

**Comment by AaronGullickson** [comment]
Columbus (Epsilon Pegausus) should also be a planetary waystation. Technically, Explorer Corps has information about the whole system, so the generated stuff will need to be overwritten by hand.

**Comment by AaronGullickson** [comment]
Dark Nebula is also a waystation. Where is it detailed?

**Comment by AaronGullickson** [comment]
What is "EC821-387D" located NE of the clan pentagon worlds?

EDIT  - I found the information on Sarna. This was the site of a major naval battle. Its an unihabited system that was never colonized, so it should just go in connectors.

**Comment by AaronGullickson** [comment]
I also see three "Interstellar Expeditions" planets:

Skyfog
Rover
Rest Stop

I assume all of these are waystations?

**Comment by AaronGullickson** [comment]
There are also three "Interstellar Expedition Bae #" entries - 6, 14, 22. Presumably these are all waystations.

**Comment by AaronGullickson** [comment]
St. Jean, Gwithian, and Nouveaux Paris all have a first entry in 3049 for the clan, so even though its later than 3047, it is their first and therefore only entry. I think we should probably put in a non-canon date of faction IND to establish the independent colonies here. I would recommend just going with 2800 so the colony pop sizes are kept pretty small.

**Comment by HammerGS** [comment]
Re- Dark Nebula that would be Camelot Command. So information I've found.

Twelfth Fleet was previously based out of a Star League base hidden in the Dark Nebula. Nearly impossible to find without the exact coordinates, it provides an excellent base of operations for
the fleet. While leave while in port allowed little for the crew to do, it is almost as safe as Sol itself. There were rumors of advanced technology and AI construction facilities.  FM:SLDF pg 156

From Objective Clans pg 10 side note this page also covers Star's End.
![image](https://user-images.githubusercontent.com/13752452/64547596-1d768e80-d2ea-11e9-9ffd-9b45401ff6a0.png)

Lastly this Sarna page is a good summary of Camelot Command - https://www.sarna.net/wiki/Camelot_Command

**Comment by jayof9s** [comment]
To add onto that, Dark Nebula is also apparently a (star) cluster so Camelot Command is at just one of many stars in the nebula.

I don't think any of the other systems in there are detailed but I did see a reference to some of them being inhabited.

**Comment by AaronGullickson** [comment]
🤦‍♂ star clusters. Had some ideas while out walking the dog, but not for this PR. 

Can I get some input on Intersellar Expeditions Base 6, 14, and 22 and the Skyfog, Rover, and Rest Stop. Any idea if they are orbital or surface bases?

**Comment by AaronGullickson** [comment]
Ok just found infor in ISP3. It looks like no details on the three bases so I will assume they are orbital. I think all of the IE planets are are archeological digs. That presents some problems as they were all abandoned at some point and then re-colonized by IE. However, the re-colonization is really just an archeological dig. However, for example, Skyfog is coming in with a population of 24 million in 3048. There are a small enough number of cases here that we may just want to edit by hand, but I might be able to also put in a quick check for whether the faction is Interstellar Expeditions on a re-colonization and if so, set the population at a small static level.

**Comment by AaronGullickson** [comment]
Commit aac2f78 adds waystation generation. I am going to wait to merge the branch and close this until I address the IE archeological dig issue.

**Comment by AaronGullickson** [comment]
This has now been merged into the master branch.
