### ISSUE TITLE
System position and renamed planets

### ISSUE THREAD

**Issue by AaronGullickson** [AaronGullickson/system_generation#9]
We are using the founding name of a planet to determine if there is an implied system position (e.g. Deneb II is the second planet). We also name other planets with the same base but numerical suffixes in cases like this. 

However, we do not make adjustments for planet name changes. There are two kinds of name changes we need to think about.

1. Planets that changed from a non-system position name to a system position name. There appears to be two of these currently. Himmels changed to Baltazar III and Green Stone changed to Clayborne II. There is also the case of Hope IV becoming Randis IV, which maintains the numbering but changes the base name. 
2. Planets that changed from a system position name to a non-system position name. There appears to be one of these currently. Carver V changed its name to Liberty.

To handle these cases, I would recommend when processing the name change data, we put in checks for each case and handle them as follows: 

1. non-numeric to numeric. Put in a name change for all planets in the system, with the new base name and a numeric value. 
2. numeric to non-numeric. This one I am more undecided about. We could leave as is. So in the one case we have, all of the other planets in the system would be Carver I, Carver II, etc, and then Carver V would be Liberty. Or we could rename all planets. My instinct is to go with the former, particularly for the one case we have.

**Comment by NickAragua** [comment]
For 1, I have no idea. Semantically, it depends on if it's the planet name that changed or the system name, but in Battletech, planet name = system name. So, for practical purposes, I'd say do a full system rename in that case. 
For 2, yeah, let's go with "Carver I, Carver II... , Liberty, Carver VI"

**Comment by HammerGS** [comment]
I agree with NickAragua on both accounts.

**Comment by AaronGullickson** [comment]
The indicated commit above should fix this issue. I have decided to go with the solution suggested by @NickAragua
